import { ProductType, ProductVariant } from './types';

export const PRODUCT_VARIANTS: Record<ProductType, ProductVariant[]> = {
  tshirt: [
    {
      id: 'hoodie-black',
      name: 'Buso Verde',
      imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      basePrice: 45,
      bounds: { top: 100, left: 100, right: 460, bottom: 500 },
      gender: 'hombre',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'back',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'left',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'right',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
      ],
    },
    {
      id: 'hoodie-black',
      name: 'Buso Verde',
      imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      basePrice: 45,
      bounds: { top: 100, left: 100, right: 460, bottom: 500 },
      gender: 'hombre',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'back',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'left',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'right',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
      ],
    },
    {
      id: 'hoodie-black',
      name: 'Buso Verde',
      imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      basePrice: 45,
      bounds: { top: 100, left: 100, right: 460, bottom: 500 },
      gender: 'hombre',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'back',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'left',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'right',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
      ],
    },
    {
      id: 'hoodie-black',
      name: 'Buso Verde',
      imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      basePrice: 45,
      bounds: { top: 100, left: 100, right: 460, bottom: 500 },
      gender: 'hombre',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'back',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'left',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'right',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
      ],
    },
    {
      id: 'hoodie-black',
      name: 'Buso Verde',
      imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      basePrice: 45,
      bounds: { top: 100, left: 100, right: 460, bottom: 500 },
      gender: 'hombre',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'back',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'left',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'right',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
      ],
    },
    {
      id: 'hoodie-black',
      name: 'Buso Verde',
      imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      basePrice: 45,
      bounds: { top: 100, left: 100, right: 460, bottom: 500 },
      gender: 'hombre',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'back',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'left',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'right',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
      ],
    },
    {
      id: 'hoodie-black',
      name: 'Buso Verde',
      imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      basePrice: 45,
      bounds: { top: 100, left: 100, right: 460, bottom: 500 },
      gender: 'hombre',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'back',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'left',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'right',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
      ],
    },
    {
      id: 'hoodie-black',
      name: 'Buso Verde',
      imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      basePrice: 45,
      bounds: { top: 100, left: 100, right: 460, bottom: 500 },
      gender: 'hombre',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'back',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'left',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'right',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
      ],
    },
    {
      id: 'hoodie-black',
      name: 'Buso Verde',
      imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      basePrice: 45,
      bounds: { top: 100, left: 100, right: 460, bottom: 500 },
      gender: 'hombre',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'back',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'left',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'right',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
      ],
    },
    {
      id: 'hoodie-black',
      name: 'Buso Verde',
      imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      basePrice: 45,
      bounds: { top: 100, left: 100, right: 460, bottom: 500 },
      gender: 'hombre',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'back',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'left',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'right',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
      ],
    },
    {
      id: 'hoodie-black',
      name: 'Buso Verde',
      imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      basePrice: 45,
      bounds: { top: 100, left: 100, right: 460, bottom: 500 },
      gender: 'hombre',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'back',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'left',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'right',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
      ],
    },
    {
      id: 'hoodie-black',
      name: 'Buso Verde',
      imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
      basePrice: 45,
      bounds: { top: 100, left: 100, right: 460, bottom: 500 },
      gender: 'hombre',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/camisaamarillafrente.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'back',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/busoamarilloespalda.png',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'left',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'right',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellafosforecente-side2.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
      ],
    },
    {
      id: 'hoodie-gray',
      name: 'Buzo Gris',
      imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franelagris.webp',
      thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franelagris.webp',
      basePrice: 45,
      bounds: { top: 100, left: 100, right: 460, bottom: 500 },
      gender: 'mujer',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franelagris.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franelagris.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'back',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franelagris-back.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franelagris-back.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'left',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franelagris-side.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franelagris-side.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'right',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franelagris-side2.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franelagris-side2.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
      ],
    },
    {
      id: 'sweatshirt-black',
      name: 'Buzo Naranja',
      imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellamarilla.webp',
      thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellamarilla.webp',
      basePrice: 40,
      bounds: { top: 100, left: 100, right: 460, bottom: 500 },
      gender: 'juvenil',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellamarilla.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellamarilla.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'back',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellamarilla-back.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellamarilla-back.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'left',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellamarilla-side.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellamarilla-side.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
        {
          view: 'right',
          imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellamarilla-side2.webp',
          thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/camisas/franellamarilla-side2.webp',
          bounds: { top: 100, left: 100, right: 460, bottom: 500 },
        },
      ],
    },
  ],
  cap: [
    {
      id: 'cap-dad',
      name: 'Gorra Clásica',
      imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/gorras/gorra%20roja.webp',
      thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/gorras/gorra%20roja.webp',
      basePrice: 25,
      bounds: { top: 60, left: 200, right: 360, bottom: 180 },
      gender: 'hombre',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://printwear.vercel.app/cap-classic.png',
          thumbnailUrl: 'https://printwear.vercel.app/cap-classic-thumb.png',
          bounds: { top: 60, left: 200, right: 360, bottom: 180 },
        },
        {
          view: 'back',
          imageUrl: 'https://printwear.vercel.app/cap-classic-back.png',
          thumbnailUrl: 'https://printwear.vercel.app/cap-classic-back-thumb.png',
          bounds: { top: 60, left: 200, right: 360, bottom: 180 },
        },
        {
          view: 'left',
          imageUrl: 'https://printwear.vercel.app/cap-classic-side.png',
          thumbnailUrl: 'https://printwear.vercel.app/cap-classic-side-thumb.png',
          bounds: { top: 60, left: 200, right: 360, bottom: 180 },
        },
        {
          view: 'right',
          imageUrl: 'https://printwear.vercel.app/cap-classic-side2.png',
          thumbnailUrl: 'https://printwear.vercel.app/cap-classic-side2-thumb.png',
          bounds: { top: 60, left: 200, right: 360, bottom: 180 },
        },
      ],
    },
    {
      id: 'cap-snapback',
      name: 'Gorra Snapback',
      imageUrl: 'https://printwear.vercel.app/cap-snapback.png',
      thumbnailUrl: 'https://printwear.vercel.app/cap-snapback-thumb.png',
      basePrice: 28,
      bounds: { top: 70, left: 190, right: 370, bottom: 170 },
      gender: 'mujer',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://printwear.vercel.app/cap-snapback.png',
          thumbnailUrl: 'https://printwear.vercel.app/cap-snapback-thumb.png',
          bounds: { top: 70, left: 190, right: 370, bottom: 170 },
        },
        {
          view: 'back',
          imageUrl: 'https://printwear.vercel.app/cap-snapback-back.png',
          thumbnailUrl: 'https://printwear.vercel.app/cap-snapback-back-thumb.png',
          bounds: { top: 70, left: 190, right: 370, bottom: 170 },
        },
        {
          view: 'left',
          imageUrl: 'https://printwear.vercel.app/cap-snapback-side.png',
          thumbnailUrl: 'https://printwear.vercel.app/cap-snapback-side-thumb.png',
          bounds: { top: 70, left: 190, right: 370, bottom: 170 },
        },
        {
          view: 'right',
          imageUrl: 'https://printwear.vercel.app/cap-snapback-side2.png',
          thumbnailUrl: 'https://printwear.vercel.app/cap-snapback-side2-thumb.png',
          bounds: { top: 70, left: 190, right: 370, bottom: 170 },
        },
      ],
    },
    {
      id: 'cap-beanie',
      name: 'Gorra Beanie',
      imageUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/gorras/gorra%20negra.jpg',
      thumbnailUrl: 'https://eaa5q8xpiwhdnz0x.public.blob.vercel-storage.com/gorras/gorra%20negra.jpg',
      basePrice: 22,
      bounds: { top: 50, left: 180, right: 380, bottom: 160 },
      gender: 'niños',
      defaultAngle: 'front',
      angles: [
        {
          view: 'front',
          imageUrl: 'https://printwear.vercel.app/cap-beanie.png',
          thumbnailUrl: 'https://printwear.vercel.app/cap-beanie-thumb.png',
          bounds: { top: 50, left: 180, right: 380, bottom: 160 },
        },
        {
          view: 'back',
          imageUrl: 'https://printwear.vercel.app/cap-beanie-back.png',
          thumbnailUrl: 'https://printwear.vercel.app/cap-beanie-back-thumb.png',
          bounds: { top: 50, left: 180, right: 380, bottom: 160 },
        },
        {
          view: 'left',
          imageUrl: 'https://printwear.vercel.app/cap-beanie-side.png',
          thumbnailUrl: 'https://printwear.vercel.app/cap-beanie-side-thumb.png',
          bounds: { top: 50, left: 180, right: 380, bottom: 160 },
        },
        {
          view: 'right',
          imageUrl: 'https://printwear.vercel.app/cap-beanie-side2.png',
          thumbnailUrl: 'https://printwear.vercel.app/cap-beanie-side2-thumb.png',
          bounds: { top: 50, left: 180, right: 380, bottom: 160 },
        },
      ],
    },
  ],
};

// Price per 1000 square pixels
export const PRICE_PER_AREA_MULTIPLIER = 0.05;

export const INITIAL_DESIGN_WIDTH = 100;